title: Kevin Wang Ji # your name (or website title) here
logo: "/images/Headshot_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center>New York, US</center>
  <br style="line-height: 1px" />
  Analytical and strategic minded professional with venture capital and start up experience currently pursuing a master’s degree in the field of data analytics. 
  <br><br>
  Skilled in Python, SQL, R, Tableau, Excel, Data Analysis and Machine Learning 
  <br><br>
  <a href="https://www.linkedin.com/in/kevinwangji/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
